"""cria tabela atividades

Revision ID: 1e97d0dd461a
Revises: 1e2a7d11468f
Create Date: 2026-09-22 21:47:22.016936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e97d0dd461a'
down_revision: Union[str, Sequence[str], None] = '1e2a7d11468f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('local', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('nova_faixa', sa.String(length=120), nullable=True),
    sa.Column('presenca', sa.Boolean(), nullable=True),
    sa.Column('dono_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['dono_id'], ['usuarios.id'], name='fk_atividades_dono'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atividades_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atividades_id'))

    op.drop_table('atividades')
    # ### end Alembic commands ###
