"""alunos e  usuarios

Revision ID: 5e6ec5e72f1e
Revises: 
Create Date: 2026-09-17 20:26:38.007232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6ec5e72f1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('faixa', sa.String(length=120), nullable=False),
    sa.Column('turma', sa.String(length=120), nullable=False),
    sa.Column('tamanho_kimono', sa.String(length=5), nullable=True),
    sa.Column('tamanho_faixa', sa.String(length=5), nullable=True),
    sa.Column('codigo_zempo', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alunos_id'), ['id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_id'))

    op.drop_table('alunos')
    # ### end Alembic commands ###
