"""dono_id em livros

Revision ID: 89e41bf30cd8
Revises: 5e6ec5e72f1e
Create Date: 2026-09-17 20:41:23.547114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e41bf30cd8'
down_revision: Union[str, Sequence[str], None] = '5e6ec5e72f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
